### ISSUE TITLE
Use selected episode to filter search 

### ISSUE THREAD

**Issue by kirushik** [SUSE/hackweek#108]
Currently we're searching globally. It's not that great, as closer to the start of HW12 we most probably would want to limit the default scope to the HW12 projects.

**Comment by KauNair** [comment]
Sounds interesting! Can I work on this?

**Comment by DavidKang** [comment]
@KauNair, go ahead :smile:

**Comment by KauNair** [comment]
Sorry for late response, I had my semester exams. I need some help regarding this. 
I am able to search according to episode on the list of projects page.I also changed the search route url to ":episode/search".  But I cannot search on other pages since I need the episode id in the params hash. To change this I'll have to add :episode to all the urls. Should I do that or remove search bar from other pages?

**Comment by hennevogel** [comment]
@KauNair why do you need to change the routes? Isn't this just a matter of using `@episode` in `SearchController` as a [sphinx filter](https://freelancing-gods.com/thinking-sphinx/searching.html#filters)?

**Comment by KauNair** [comment]
Yes. But to obtain `@episode` I need the selected episode's id.
Quick question: Do you want to have filtered only for the current hackweek or also for previous hackweeks?

**Comment by hennevogel** [comment]
@KauNair `ApplicationController` already obtains `@episode` for you in a `before_filter`

**Comment by hennevogel** [comment]
> Do you want to have filtered only for the current hackweek or also for previous hackweeks?

I want it filtered for whatever `Episode` I'm looking at (or all if no `Episode`)

**Comment by KauNair** [comment]
When I search, the params only contain the search query. So the `ApplicationController` resets `@episode` to active episode
`  
    if params[:episode].blank?
       @episode = Episode.active
   `

But I managed to pass it in a hidden field so it works now. 
PR created.
Thanks for the help!

**Comment by DavidKang** [comment]
Addressed on PR #297
