### ISSUE TITLE
Speed up the initial page load

### ISSUE THREAD

**Issue by kirushik** [SUSE/hackweek#110]
Currently it is slow, as we are loading and rendering all the projects in the DB.
We can use the brand-new Rails russian-doll caching for our partials (and maybe also some tricky-to-calculate objects), but we'd better install MemCache or (personal preference) Redis instance for that.

We can also use pagination for projects browsing, but that would require some really fast and smooth search, otherwise our users (especially the keyboard lovers) will be upset.

**Comment by hennevogel** [comment]
Initial page load would be faster if we fix #105

**Comment by kirushik** [comment]
@hennevogel but:
 - it's fun to do;
 - it's good to have some comparatively uncomplicated playground for that new tech, we have some Redis caching in our SCC roadmap;
 - we can also easily cache typical searches, significantely speeding up typical searches for #111.
 - we're getting Redis, which might also come in handy for some Sidekiq-baked background workers, for example (and I have couple of great ideas how to use those, not for the short-term plan).

I can (and want) to take care of that, given we will have something to automate components deployment (#106 related).

**Comment by hennevogel** [comment]
I absolutely agree that it's nice to play around with new tech stuff, I'm just afraid that this is not going to lead to a more solid hack week app ;-) I would rather like to keep it simple, stupid for now.

Especially because contributors come and go in this project depending on which department organizes an hack week episode. And once they go they usually leave me behind with their messy playground...

**Comment by kirushik** [comment]
@hennevogel OK, objection accepted. I will spend my efforts to other issues, and return to caching topic a week before Hackweek, so we can re-evaluate its risks and profits.
